### ISSUE TITLE
Support semi-permanent temp dirs with `setUpAll` and `tearDownAll`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test_descriptor#11]
Today integration tests are often slow because you have to create a whole new package dir for every test, and re-run pub get etc within that directory.

Ideally, this would be automatic so that any descriptors created inside of `setUpAll` didn't get deleted until after `tearDownAll`, but any descriptors created in `setUp` would still get deleted inside of `tearDown`. This would make the logic for cleaning up files more complicated though, especially when you take into account that some users use file apis directly by grabbing the sandbox dir.

Another option could be creating an additional class, lets call it `Sandbox`. This class would have all the same descriptor methods that exist at the top level, and it would expose a `delete` method, which you have to explicitly call (typically inside tearDownAll). All the top level descriptor methods would change to use a default `Sandbox` instance which gets deleted by default inside `tearDown`.

**Comment by nex3** [comment]
I'm curious how you intend to delete only the test-specific files without deleting cross-test files. What would that code look like?

One way to solve this without changing this package at all would be to change `addTearDown()` in `test` to add a suite-level tear-down when called from `setUpAll()`. This may be a good idea anyway, since it would make a lot of code that was written for test-level transparently work at the suite level as well.

**Comment by jakemac53** [comment]
> I'm curious how you intend to delete only the test-specific files without deleting cross-test files. What would that code look like?

You could call `addTearDown()` whenever anybody calls one of the descriptor methods, with a method which will clean up specifically that descriptor (instead of the whole sandbox). This would be a suite level tear-down if inside `setUpAll`,  or test level otherwise.

There would still need to be a hook to clean up the entire dir at the end though, and it could break existing tests that are using the file system directly inside of some tests and relying on getting a whole new sandbox in each subsequent test (otherwise they have to manually clean up any changes they make).

> One way to solve this without changing this package at all would be to change addTearDown() in test to add a suite-level tear-down when called from setUpAll(). This may be a good idea anyway, since it would make a lot of code that was written for test-level transparently work at the suite level as well.

Yes, I think that would generally be a good change, and I think it would work out of the box with this package to do what I would want.

**Comment by nex3** [comment]
> You could call `addTearDown()` whenever anybody calls one of the descriptor methods, with a method which will clean up specifically that descriptor (instead of the whole sandbox). This would be a suite level tear-down if inside `setUpAll`,  or test level otherwise.
> 
> There would still need to be a hook to clean up the entire dir at the end though, and it could break existing tests that are using the file system directly inside of some tests and relying on getting a whole new sandbox in each subsequent test (otherwise they have to manually clean up any changes they make).

This is probably logic we'd want to leave up to the individual tests... I think if we built it in we'd be running a serious risk of doing something the user didn't expect.

> Yes, I think that would generally be a good change, and I think it would work out of the box with this package to do what I would want.

Great! I've filed dart-lang/test#712 to track that, so I'm going to close this issue.
