### ISSUE TITLE
Incorrect files created when using `await` to set up the structure

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test_descriptor#15]
It's a little hard to narrow in on, heres about the smallest repro I'm able to get, changing some of the details including ordering makes it no longer occur.

```dart
import 'dart:async';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:test_descriptor/test_descriptor.dart' as d;

void main() {
  test('', () async {
    var testdir = d.dir('outer', [
      d.file('missing'),
      d.dir('a', [
        d.dir('b', [
          d.file('c'),
          d.dir('d', [d.file('e')]),
          await new Future.value(d.file('async_inner')),
        ]),
      ]),
      await new Future.value(d.file('async_outer')),
    ]);
    print(testdir.describe());
    await testdir.create();
    print(new Directory(p.join(d.sandbox, 'outer')).listSync().join('\n'));
    expect(
        await new File(p.join(d.sandbox, 'outer', 'missing')).exists(), true);
  });
}
```

For some reason having the `await`s causes the `'c'` file to show up twice, once in place of `'missing'`.

**Comment by jakemac53** [comment]
Note that this appears to only happen in Dart 2 - not sure if that means it is a Dart 2 implementation bug or something in the test descriptor package which is broken in Dart 2?

**Comment by natebosch** [comment]
Turns out this repros without test_descriptor at all. The VM has something broken with async/await in Dart 2.

https://github.com/dart-lang/sdk/issues/33660
