### ISSUE TITLE
`read` on a non-existent file should return null or throw

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test_descriptor#6]
```dart
var content = await d.file('file_not_here').read();
print(content.length);
```

expected: read throws or content.length throws (because content is null)
actual: prints `0`

**Comment by nex3** [comment]
I think you may be misunderstanding the semantics of `read()`. It doesn't read from the computer's actual filesystem; it reads from the virtual filesystem defined by the descriptors. So in this case, you're defining an empty file named `file_not_here` and reading it, which correctly returns an empty byte buffer.
